-- MySQL Script generated by MySQL Workbench
-- 06/28/16 16:32:50
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema bd_cepred
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `bd_cepred` ;

-- -----------------------------------------------------
-- Schema bd_cepred
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bd_cepred` DEFAULT CHARACTER SET utf8 ;
USE `bd_cepred` ;

-- -----------------------------------------------------
-- Table `bd_cepred`.`etudiant`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bd_cepred`.`etudiant` ;

CREATE TABLE IF NOT EXISTS `bd_cepred`.`etudiant` (
  `num_etudiant` INT NOT NULL,
  `cycle_etudiant` VARCHAR(45) NULL,
  `code_personne` INT NULL,
  `ine_etudiant` VARCHAR(45) NULL,
  PRIMARY KEY (`num_etudiant`),
  INDEX `code_personne_idx` (`code_personne` ASC),
  CONSTRAINT `code_personne`
    FOREIGN KEY (`code_personne`)
    REFERENCES `bd_cepred`.`personne` (`num_personne`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_cepred`.`personne`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bd_cepred`.`personne` ;

CREATE TABLE IF NOT EXISTS `bd_cepred`.`personne` (
  `num_personne` INT NOT NULL,
  `nom_personne` VARCHAR(45) NOT NULL,
  `prenom_personne` VARCHAR(45) NOT NULL,
  `dt_naissance_personne` VARCHAR(45) NOT NULL,
  `num_adresse_personne` VARCHAR(45) NULL,
  `type_personne` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`num_personne`, `email`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_cepred`.`adresse`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bd_cepred`.`adresse` ;

CREATE TABLE IF NOT EXISTS `bd_cepred`.`adresse` (
  `num_adresse` INT NOT NULL,
  `code_personne` INT NULL,
  `code_postal` VARCHAR(45) NULL,
  `ville` VARCHAR(45) NULL,
  `pays` VARCHAR(45) NULL,
  `libelle_adresse` VARCHAR(45) NULL,
  `rue` VARCHAR(45) NULL,
  `numero` VARCHAR(45) NULL,
  `` VARCHAR(45) NULL,
  PRIMARY KEY (`num_adresse`),
  INDEX `code_personne_idx` (`code_personne` ASC),
  CONSTRAINT `code_personne`
    FOREIGN KEY (`code_personne`)
    REFERENCES `bd_cepred`.`personne` (`num_personne`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_cepred`.`matiere`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bd_cepred`.`matiere` ;

CREATE TABLE IF NOT EXISTS `bd_cepred`.`matiere` (
  `num_matiere` INT NOT NULL,
  `nom_matiere` VARCHAR(45) NULL,
  `num_enseignant` VARCHAR(45) NULL,
  `code_matiere` INT NULL,
  `coef_matiere` INT NULL,
  `cycle_matiere` VARCHAR(45) NULL,
  `classe_matiere` VARCHAR(45) NULL,
  PRIMARY KEY (`num_matiere`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_cepred`.`note`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bd_cepred`.`note` ;

CREATE TABLE IF NOT EXISTS `bd_cepred`.`note` (
  `num_note` INT NOT NULL,
  `code_etudiant` INT NULL,
  `code_matiere` INT NULL,
  `note1` INT NULL,
  `note2` INT NULL,
  `code_enseignant` INT NULL,
  PRIMARY KEY (`num_note`),
  INDEX `code_matiere_idx` (`code_matiere` ASC),
  INDEX `code_etudiant_idx` (`code_etudiant` ASC),
  CONSTRAINT `code_matiere`
    FOREIGN KEY (`code_matiere`)
    REFERENCES `bd_cepred`.`matiere` (`num_matiere`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `code_etudiant`
    FOREIGN KEY (`code_etudiant`)
    REFERENCES `bd_cepred`.`etudiant` (`num_edtudiant`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_cepred`.`etudiant`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bd_cepred`.`etudiant` ;

CREATE TABLE IF NOT EXISTS `bd_cepred`.`etudiant` (
  `num_etudiant` INT NOT NULL,
  `cycle_etudiant` VARCHAR(45) NULL,
  `code_personne` INT NULL,
  `ine_etudiant` VARCHAR(45) NULL,
  PRIMARY KEY (`num_etudiant`),
  INDEX `code_personne_idx` (`code_personne` ASC),
  CONSTRAINT `code_personne`
    FOREIGN KEY (`code_personne`)
    REFERENCES `bd_cepred`.`personne` (`num_personne`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_cepred`.`enseignant`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bd_cepred`.`enseignant` ;

CREATE TABLE IF NOT EXISTS `bd_cepred`.`enseignant` (
  `num_enseignant` INT NOT NULL,
  `num_matiere` VARCHAR(45) NULL,
  `code_personne` INT NULL,
  PRIMARY KEY (`num_enseignant`),
  INDEX `code_personne_idx` (`code_personne` ASC),
  CONSTRAINT `code_personne`
    FOREIGN KEY (`code_personne`)
    REFERENCES `bd_cepred`.`personne` (`num_personne`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
